### ISSUE TITLE
Running the .dmg on macOS yields an error 'Error: Cannot read properties of null (readig 'withFileTypes')'

### ISSUE THREAD

**Issue by bierlingm** [coasys/flux#136]
<img width="2032" alt="Screen Shot 2021-10-13 at 12 25 30" src="https://user-images.githubusercontent.com/9335771/137115843-de263e5d-2d14-4260-9ccd-695dabc81a27.png">

**Comment by jdeepee** [comment]
> > Thanks for reporting @bierlingm could you also include your log file which can be found at: `/Users/<YOURUSERNAME>/Library/Application\ Support/junto/debug.log`
> 
> Strangely enough I can't find a 'debug.log' file at the indicated place, but there is another log file I'll attach here.
> 
> [000003.log](https://github.com/juntofoundation/flux/files/7337768/000003.log)

Okay interesting ill ship something today that allows for the copying of this log file to the desktop. I think this `withFileTypes` value is a parameter in some `fs` calls so its possible it is just failing to create the log file altogether and that is the reason for the error in the first place haha
